# Generated by Django 5.0.14 on 2026-05-07 15:36

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('VIEW', '閲覧')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.BigIntegerField()),
                ('summary', models.CharField(default='', max_length=500)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='wiki_auditl_action_54ddaa_idx'), models.Index(fields=['model_name', 'object_id'], name='wiki_auditl_model_n_f18ccf_idx'), models.Index(fields=['created_at'], name='wiki_auditl_created_b3e645_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, default='', max_length=16)),
                ('has_mermaid', models.BooleanField(db_index=True, default=False)),
                ('bookmark', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '整理済')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='wiki.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='wiki.tag')),
            ],
            options={
                'ordering': ['-bookmark', '-updated_at'],
                'indexes': [models.Index(fields=['status'], name='wiki_note_status_ddbd6b_idx'), models.Index(fields=['bookmark'], name='wiki_note_bookmar_233265_idx'), models.Index(fields=['updated_at'], name='wiki_note_updated_a46b00_idx'), models.Index(fields=['title'], name='wiki_note_title_69c9aa_idx'), models.Index(fields=['content_hash'], name='wiki_note_content_b17a2a_idx')],
            },
        ),
    ]
