# Generated by Django 5.0.14 on 2026-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_hash'], name='wiki_note_content_b17a2a_idx'),
        ),
    ]
